-- apply changes
create table urls (
  id                            bigint generated by default as identity not null,
  protocol                      varchar(255),
  host                          varchar(255),
  port                          integer,
  created_at                    timestamp not null,
  constraint pk_urls primary key (id)
);

