ebean:
  migration:
    run: true       # run database migrations on startup

datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./myDB"
#   driver: org.h2.Driver
  production:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}
#   driver: org.postgresql.Driver


