name: build
on:
  push:
    branches:
      - main

jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - run: ./gradlew build
    steps:
    - name: Test & publish code coverage
    uses: paambaati/codeclimate-action@v3.0.0
    env:
      CC_TEST_REPORTER_ID: ${{secrets.TEST_REPORTER_ID}}
      JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
    with:
      coverageCommand: mvn test
      coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco
